### PR TITLE
Enable feature `all` on socket2

### PR DESCRIPTION
**Pull request by wathiede**
This addresses issue #5

### CODE REVIEW

**Comment by wathiede** [comment]
Dropping per https://github.com/cloudflare/foundations/issues/5#issuecomment-1920441200

**Comment by Noah-Kennedy** [comment]
See [my comment in the issue](https://github.com/cloudflare/foundations/issues/5#issuecomment-1920457904), but I think this should be reopened and merged.

**Comment by wathiede** [comment]
Sorry I was so quick to close.

**Comment by Noah-Kennedy** [comment]
> Sorry I was so quick to close.

No worries!

**Review by Noah-Kennedy — APPROVED** [review]

**Pull request merged**
