### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by bcottrell8738**
My motivation for proposing a release is that I would like to get https://github.com/cloudflare/foundations/pull/47

I was figuring a "minor" bump for that, but I'm open to different viewpoints.

### CODE REVIEW

**Comment by nmldiegues** [comment]
Clippy isn't happy

**Review by fisherdarling — CHANGES_REQUESTED** [review]
Can we run `cargo-semver-checks` to determine the level of breaking changes? Since we don't track manually what's breaking or not, it's hard to tell from the RELEASE_NOTES.

**Comment by bcottrell8738** [comment]
> Can we run `cargo-semver-checks` to determine the level of breaking changes? Since we don't track manually what's breaking or not, it's hard to tell from the RELEASE_NOTES.

cargo semver-checks says it needs to be a major version (!) -- I don't know if that also means we want more coordination around the timing of this. I was just hoping to get my change in there, but maybe my change should take a back seat.

**Comment by fisherdarling** [comment]
> > Can we run `cargo-semver-checks` to determine the level of breaking changes? Since we don't track manually what's breaking or not, it's hard to tell from the RELEASE_NOTES.
> 
> cargo semver-checks says it needs to be a major version (!) -- I don't know if that also means we want more coordination around the timing of this. I was just hoping to get my change in there, but maybe my change should take a back seat.

Like it's suggesting `4.0.0`? That's fine! Whatever the semver gods require.

**Pull request closed without merging**
